-d D:\proj\nano4k_dvitx_ov2640\project\impl\gwsynthesis\test_top.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst D:\proj\nano4k_dvitx_ov2640\project\src\test_top.cst
-cfg D:\proj\nano4k_dvitx_ov2640\project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
